### ISSUE TITLE
End to end benchmark results

### ISSUE THREAD

**Issue by llhe** [pytorch/QNNPACK#1]
Thanks for the great project!

Is there end to end benchmark results over common networks?

**Comment by clhne** [comment]
FYI. 
[QNNPACK: Open source library for optimized mobile deep learning](https://code.fb.com/ml-applications/qnnpack/)

**Comment by Maratyszcza** [comment]
The blog post referenced by @clhne contains end-to-end benchmarks against TensorFlow Lite. Here's how you can benchmark end-to-end yourself on ARMv7 build of PyTorch 1.0 + QNNPACK and [Caffe2 MobileNet v2 model](https://github.com/caffe2/models/tree/master/mobilenet_v2_quantized):
```bash
git clone --recursive https://github.com/pytorch/pytorch.git
cd pytorch
scripts/build_android.sh -DBUILD_BINARY=ON
adb push build_android/bin/speed_benchmark /data/local/tmp/speed_benchmark
wget https://s3.amazonaws.com/download.caffe2.ai/models/mobilenet_v2_1.0_224_quant/init_net.pb
adb push init_net.pb /data/local/tmp/
wget https://s3.amazonaws.com/download.caffe2.ai/models/mobilenet_v2_1.0_224_quant/predict_net.pb
adb push predict_net.pb /data/local/tmp/
adb shell /data/local/tmp/speed_benchmark --init_net /data/local/tmp/init_net.pb --net /data/local/tmp/predict_net.pb --input data --input_dims 1,3,224,224 --input_type float --iter 10 --warmup 100
```
