### ISSUE TITLE
Can I convert a PyTorch model in float to qnnpack model

### ISSUE THREAD

**Issue by ryanqiutu** [pytorch/QNNPACK#10]
Excuse me:
   Can I convert a PyTorch model in float to QNNPACK model just because I train the model using PyTorch in float?

**Comment by Maratyszcza** [comment]
As of today, the QNNPACK can be used only from Caffe2 backend of PyTorch 1.0. We are working on converters and API to expose QNNPACK directly from PyTorch frontend and graph representation.

**Comment by ryanqiutu** [comment]
Thank for your answer. How can I get the QNNPACK model for caffe2. Before I used onnx to convert the model to caffe2 model and the model can run using nnpack. But now how can I convert the model to caffe2 model using qnnpack?

**Comment by Maratyszcza** [comment]
We haven't released the tooling for converting floating-point models to quantized (8-bit) models yet. You may use QNNPACK with the two pre-trained models that we released:
- ResNet-50: https://github.com/caffe2/models/tree/master/resnet50_quantized
- MobileNet v2: https://github.com/caffe2/models/tree/master/mobilenet_v2_quantized

**Comment by ryanqiutu** [comment]
Thanks. I've tested the model. The results seem good.
