### ISSUE TITLE
Performance benchmark on GPUs, NPUs

### ISSUE THREAD

**Issue by chaos5958** [pytorch/QNNPACK#11]
Great project! I hope QNNPACK makes mobile deployment much easier.

1. Can models from QNNPACK run on mobile GPUs or NPUs (e.g., Snapdragon 845 DSP or Kirin 970/980)?
If so, any benchmark results compared to Tensorflow Light would be helpful.
I want to know whether QNNPACK is optimized for mobile CPUs or does not depend on the types of underlying hardware.

2. (Similar question to 1) Does QNNPACK use NNAPI that recently enabled in Android 9.0?

**Comment by Maratyszcza** [comment]
QNNPACK is not a deep learning framework, it is an inference library for mobile CPUs. It provides functions to do inference in convolutional, deconvolutional, and fully-connected operators, but no high-level objects on top of it (e.g. it doesn't even have a notion of computational graph). QNNPACK is integrated in PyTorch 1.0 with Caffe2 graph representation. See blog post for comparison of Caffe2+QNNPACK vs TensorFlow Lite: https://code.fb.com/ml-applications/qnnpack/
