### ISSUE TITLE
Error compiling on PC

### ISSUE THREAD

**Issue by orentadmor** [pytorch/QNNPACK#17]
Compiling on PC using the "local" build I get:

> CMakeFiles/q8dw-test.dir/test/q8dw.cc.o: In function `DepthwiseMicrokernelTester::test(void (*)(unsigned long, unsigned long, unsigned char const**, void const*, unsigned char*, unsigned long, unsigned long, qnnp_conv_quantization_params const*)) const':
> q8dw.cc:(.text._ZNK26DepthwiseMicrokernelTester4testEPFvmmPPKhPKvPhmmPK29qnnp_conv_quantization_paramsE[_ZNK26DepthwiseMicrokernelTester4testEPFvmmPPKhPKvPhmmPK29qnnp_conv_quantization_paramsE]+0x14ba): undefined reference to `q8dw_ukernel_25c8__neon'
> collect2: error: ld returned 1 exit status
> CMakeFiles/q8dw-test.dir/build.make:90: recipe for target 'q8dw-test' failed

The problem is that in 'depthwise-microkernel-tester.h' references an arm-only function 'q8dw_ukernel_25c8__neon'.
I tried bypassing it with "#if CPUINFO_ARCH_ARM || CPUINFO_ARCH_ARM64" however it still raises a segmentation fault on the benchmark when running 'DWConv5x5' (passes 'DWConv3x3')

**Comment by dzung-hoang** [comment]
I can compile successfully by setting QNNPACK_BUILD_TESTS=OFF in the build-local.sh script.

**Comment by harouwu** [comment]
hot fix landed. Please rebase. Sorry for the inconvenience
