### ISSUE TITLE
build-local.sh error!

### ISSUE THREAD

**Issue by clhne** [pytorch/QNNPACK#2]
when run build-local.sh, there's an error:
         --- LOG END ---
         error: downloading 'https://github.com/google/benchmark/archive/v1.4.1.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END -

But when i download it offline, and put it into:
"QNNPACK/build/local/deps/googlebenchmark-download/googlebenchmark-prefix/src"
there's another error:
 does not match expected value
    expected: '61ae07eb5d4a0b02753419eb17a82b7d322786bb36ab62bd3df331a4d47c00a7'
      actual: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
-- File already exists but hash mismatch. Removing...

please help~

**Comment by Maratyszcza** [comment]
You can download Google Benchmark yourself, and configure QNNPACK with `-DGOOGLEBENCHMARK_SOURCE_DIR=/path/to/google/benchmark/dir`. Alternatively, if you don't plan to build QNNPACK's micro-benchmarks, just configure it with `-DQNNPACK_BUILD_BENCHMARKS=OFF`, it will prevent downloading Google Benchmark as well

**Comment by clhne** [comment]
how to configure QNNPACK with -DGOOGLEBENCHMARK_SOURCE_DIR=/path/to/google/benchmark/dir

**Comment by Maratyszcza** [comment]
`scripts/build_local.sh -DGOOGLEBENCHMARK_SOURCE_DIR=/path/to/google/benchmark/dir`

**Comment by Maratyszcza** [comment]
Arguments to build scripts are passed as is to CMake

**Comment by clhne** [comment]
Thanks.
