### ISSUE TITLE
Weird performance gap observed for Jetson TX2

### ISSUE THREAD

**Issue by TerryTsao** [pytorch/QNNPACK#29]
I'm currently experimenting QNNPack with Caffe2 on Jetson TX2, using the official mobilenet_v2_quant.
Significant performance gap between Nvidia Denver2 CPU and ARMv8 A57 was observed and I cannot figure out why.

CPU:
HMP Dual Denver 2/2 MB L2 + Quad ARM® A57/2 MB L2

### What I observe
When I run with all 6 cores at 2GHz, I can get 15 fps performance, give or take.

When running with 2 Nvidia Denver2 cores only, it drops to around 7fps.

However, when running with 4 A57 cores only, it drops to jaw-dropping 1fps, which is shocking.

Interestingly, I also tried on a Rasp pi with 4 ARMv7 cores at 1.2 GHz (Model 2B, I think), I can achieve around 10fps performance.

### Environment
* Platform: Jetson TX2 with Jetpack 3.3.
* Caffe2: build from source using `pytorch/scripts/build_tegra_x1.sh`.
* Code snippet:

```python
p = workspace.Predictor(init_net, predict_net)
p.run([data])
```

<br/>
Can someone give me some pointers to figure out why the quad A57 cores performs so badly?

Thank you.

Edit: Profile summaries of different cpu modes are provided:
https://gist.github.com/TerryTsao/fa30ba54e660c51d5c91aafb55715d89

**Comment by Maratyszcza** [comment]
All numbers (even 6-core) seem too low. Did you try to set frequency governor to performance setting?

**Comment by Maratyszcza** [comment]
Actually, 6-core FPS in the log is ~42 FPS, which is reasonable. How do you pin Caffe2 to particular cores?

**Comment by TerryTsao** [comment]
@Maratyszcza Thank you for your reply. I didn't do anything particular to set it to cores. On TX2, I can use command `nvpmodel` to set specific modes (details for modes are here  https://www.jetsonhacks.com/2017/03/25/nvpmodel-nvidia-jetson-tx2-development-kit/).

I didn't do anything else other than setting the mode. The reason is that this is my very first experience with Caffe2 and I'm still learning to use it. It would be very helpful if you can teach me how to boost the performance.

Also, I updated the gist with three runs showing resource utilizations, if that helps.

https://gist.github.com/TerryTsao/fa30ba54e660c51d5c91aafb55715d89

Thank you!

**Comment by TerryTsao** [comment]
@Maratyszcza I apologize for misleading you with a much too simplified snippet. I'm aware of the need for warm up runs.

In fact, the snippet is more like this for measuring time.

```python
import time

p = workspace.Predictor(init_net, predict_net)
while True:
    img = np.random.randn(1, 3, 224, 224).astype(np.float32)
    start = time.time()
    results = p.run([img])
    end = time.time()
    print(end - start)
```

As for the benchmark result, I used at least 10 warm up runs with the following snippet. (10 for the ARMv8 slow case as I don't want to wait that long for the result. 50 for the quick 6-core benchmark)

```python
net_def = caffe2_pb2.NetDef()                                                                                                                    
net_def.ParseFromString(predict_net)                                        
workspace.RunNetOnce(init_net)                                                                                      
workspace.FeedBlob('data', np.random.randn(1, 3, 224, 224).astype(np.float32))
workspace.CreateNet(predict_net, True)                                      
stats = workspace.BenchmarkNet(net_def.name, 10, 20, True)        # 50, 200 for quick 6-core          
```

I did test with actual ImageNet images, btw. The network can predict correctly. The performance issue remains the same.

I'll look into the first advice you gave. I'll also try with a different TX2 machine and some other machine to see if I can get more insight to this problem.

Thanks.

**Comment by Maratyszcza** [comment]
@TerryTsao is this resolved now?

**Comment by TerryTsao** [comment]
@Maratyszcza Sorry, I've been otherwise engaged recently. I don't have much now. All I know is that on that one TX2 machine, performance drops down a cliff if enabling A53 cores only. So long as there is a Nvidia Denver2 core enabled, reasonable performance is observed. The reason is unclear at this moment, but it seems more of a Jetson TX2 issue rather than of QNNPack. Feel free to close this issue if you like. If I have more, I'll come back. Thank you!
