### ISSUE TITLE
Could you pls provide Android Apk demo?

### ISSUE THREAD

**Issue by Meicsu199345** [pytorch/QNNPACK#32]
as title

**Comment by Maratyszcza** [comment]
Android demo is clearly outside the scope of this project. Caffe2 documentation includes AI Camera tutorial, which provides this functionality: https://caffe2.ai/docs/AI-Camera-demo-android.html

**Comment by dvlee1024** [comment]
@Maratyszcza Is this demo including QnnPack? We need an apk demo with QNNPack, too .

**Comment by Maratyszcza** [comment]
@dvlee1024 This demo uses a floating-point model, and thus doesn't run on QNNPACK. But if you replace it with a fixed-point model (see https://github.com/caffe2/models/tree/master/mobilenet_v2_quantized), it will execute through QNNPACK.

**Comment by dvlee1024** [comment]
@Maratyszcza I replace the modle but ```Predictor``` init fail.

```
11-28 09:44:33.006 23757-23775/facebook.f8demo E/F8DEMO: Attempting to load protobuf netdefs...
11-28 09:44:33.099 23757-23775/facebook.f8demo E/F8DEMO: done.
    Instantiating predictor...
11-28 09:44:33.107 23757-23775/facebook.f8demo E/native: [E operator.cc:105] Cannot find operator schema for Int8GivenIntTensorFill. Will skip schema checking.
11-28 09:44:33.335 23757-23757/facebook.f8demo E/GED: ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, 7
11-28 09:44:34.668 23757-23815/facebook.f8demo E/BufferQueueProducer: [SurfaceTexture-0-23757-0](this:0xd56ff000,id:0,api:1,p:23757,c:23757) *** UNEXPECTED graphic buffer allocation result ***
11-28 09:44:34.750 23757-23815/facebook.f8demo E/BufferQueueProducer: [SurfaceTexture-0-23757-0](this:0xd56ff000,id:0,api:1,p:23757,c:23757) *** UNEXPECTED graphic buffer allocation result ***
11-28 09:44:40.901 23757-23815/facebook.f8demo E/BufferQueueProducer: [SurfaceTexture-0-23757-0](this:0xd56ff000,id:0,api:1,p:23757,c:23757) *** UNEXPECTED graphic buffer allocation result ***
```

**Comment by Maratyszcza** [comment]
looking at the error logs, it fails somewhere else, not in Caffe2

**Comment by AAAAAhuang** [comment]
@dvlee1024 so did you solve this problem yet? I still can't run the quantized model on Android.
