### ISSUE TITLE
how can I use qnnpack to recognize a cat?

### ISSUE THREAD

**Issue by dvlee1024** [pytorch/QNNPACK#34]
Any demo for me to learn?

**Comment by jinfagang** [comment]
@dvlee1024 There were no tutorial, just checkout the apis

**Comment by Maratyszcza** [comment]
@dvlee1024 You can use Caffe2 with pre-trained [quantized MobileNet v2 classification model](https://github.com/caffe2/models/tree/master/mobilenet_v2_quantized). The model was pre-trained on ImageNet dataset, which includes several classes for cats of different cat breeds. Integration of the quantized model is no different than integration of any other Caffe2 model, you may find [tutorial here](https://caffe2.ai/docs/AI-Camera-demo-android.html)
