### ISSUE TITLE
How can I create a quantized model by QNNPACK? 

### ISSUE THREAD

**Issue by Meicsu199345** [pytorch/QNNPACK#35]

**Comment by Maratyszcza** [comment]
The tooling to quantize a model is not yet released, but will be released soon. Today you can try QNNPACK with pre-trained [quantized MobileNet v2 model](https://github.com/caffe2/models/tree/master/mobilenet_v2_quantized).

**Comment by xiezheng-cs** [comment]
Thank you for you great work!  It's really amazing！I'm looking forward to the tool of converting floating-point models to quantized (8-bit) models.
