### ISSUE TITLE
multi-thread problem.

### ISSUE THREAD

**Issue by l1a0t1n9** [pytorch/QNNPACK#36]

**Comment by l1a0t1n9** [comment]
i found qnnp_run_operator run faster when set the threadpool var to nullptr than  set the threadpool to 1~4 thread num.

**Comment by l1a0t1n9** [comment]
so how many thread is opened by default within the qnnpack_run_operator func.

**Comment by l1a0t1n9** [comment]
in my experiments,  the default performance（set the threadpool to nullptr） is similar to set the threadpool to 4 threads.

**Comment by Maratyszcza** [comment]
which thread pool implementation do you use? pthreadpool library is not very efficient, but Caffe2 reimplements pthreadpool interface on top of its own (a lot more efficient thread pool)

**Comment by l1a0t1n9** [comment]
yes, i used pthreadpool.  i‘ll  look into caffe2.

**Comment by l1a0t1n9** [comment]
In the past few days, I have rewrite the threadpool like caffe2, and the computation speed has been greatly improved, so I would like to know if you have any plans to add a custom threadpool library.

**Comment by Maratyszcza** [comment]
I have plans to upstream Caffe2 threadpool modifications to pthreadpool, but this is not the first priority right now.
