### ISSUE TITLE
Interested in using QNNPACK operators as part of another C++ library

### ISSUE THREAD

**Issue by Nimitz14** [pytorch/QNNPACK#41]
How ready is QNNPACK for that? I don't mind writing my own code to convert my model into the quantised format.

**Comment by Maratyszcza** [comment]
If you mean "is QNNPACK ready for production?", it is. Facebook apps use it for many months already.

**Comment by Nimitz14** [comment]
Sorry I'm not that knowledgeable about this sort of stuff (and would have preferred to ask elsewhere rather than open an issue, but I didn't know where). Thank you for the quick reply.
