### ISSUE TITLE
No documentation? or how to execute a layer in QNNPACK

### ISSUE THREAD

**Issue by Nimitz14** [pytorch/QNNPACK#42]
There doesn't seem to be documentation of any form? It doesn't need to be extensive, just something that gives a brief introduction to how QNNPACK is meant to be used.

For example, I want to try out using QNNPACK for executing a fully connected layer. To try and figure out how to do that, I've been looking at [caffe2's `int8_fc_op.h`](https://github.com/pytorch/pytorch/blob/master/caffe2/operators/quantized/int8_fc_op.h).  
Have I correctly understood that the first time I want to execute the layer, I need to call `qnnp_create_fully_connected_nc_q8`, then `qnnp_setup_fully_connected_nc_q8`, and then `qnnp_run_operator` ? And if I want to execute it again, I do the same but without calling `qnnp_setup_fully_connected_nc_q8` (if the batch size has not changed)?

Also, why is `inputPtr` offset by 8 (like [here](https://github.com/pytorch/QNNPACK/blob/master/test/fully-connected-operator-tester.h#L123))?

**Comment by Maratyszcza** [comment]
Right, documentation is not a strong point in QNNPACK right now.
You call `qnnp_create_fully_connected_nc_q8` as soon as you have all information needed for it (in Caffe2 it happens only on the first run, but in other frameworks you could create it as soon as a model graph is loaded). You call `qnnp_setup_fully_connected_nc_q8` when input shape or pointer has changed, but you can as well call it before each inference run (performance overhead for this function is small, albeit for `qnnp_setup_[de]convolution` it is non-negligible). You call `qnnp_run_operator` to do actual inference. You can call `qnnp_run_operator` multiple times without calling `qnnp_setup_fully_connected_nc_q8` if input & output shape and pointers didn't change. In the end you call `qnnp_delete_operator` to free QNNPACK operator object.

In some situations QNNPACK operators can read up to 7 bytes **before** input data (I think we'll remove this constraint in the future, but it is there right now):
- Fully connected operator with less than 8 input channels
- Non-depthwise convolution operator with less than 8 input channels per group
- Deconvolution operator with less than 8 input channels per group
- Depthwise convolution operator with less than 8 groups

You can either make your memory allocator always allocate extra 8 bytes before the tensor data, or copy input to a temporary buffer with extra 8 bytes of padding before the data.

**Comment by Nimitz14** [comment]
I have another question: The biases are `int32`, how is one supposed to quantize them to that?

**Comment by Nimitz14** [comment]
I have another question: The biases are int32, how is one supposed to quantize them to that?

**Comment by Nimitz14** [comment]
Thank you

**Comment by Nimitz14** [comment]
Sorry I have to ask, I don't get how why the bias tensor would have a zero point of 0? How will one represent negative numbers?

**Comment by Maratyszcza** [comment]
@Nimitz14 bias is signed `int32_t`, so negative numbers are represented as is

**Comment by Nimitz14** [comment]
Ah right of course. Thank you!
