### ISSUE TITLE
No performance difference between ARMv7 (32-bit) Android and ARM64 (64-bit) Android

### ISSUE THREAD

**Issue by yangwenca** [pytorch/QNNPACK#47]
I follow the tutorial to run speed benchmark (MobileNet v2) on ARMv7 (32-bit) and ARM64 (64-bit) Android. There is no performance difference between them.

Data from a few Android devices

device | per iter (ms) | iters per second
-- | -- | --
oneplus_5_32 | 17.27 | 57.92
oneplus_5_64 | 15.3 | 65.36
htc_10_32 | 35.56 | 28.12
htc_10_64 | 37.63 | 26.57
huawei_caml21_32 | 52.34 | 19.14
huawei_caml21_64 | 49.89 | 20.05

**Comment by Maratyszcza** [comment]
This is expected. On well-optimized code there is only a small difference between 32-bit and 64-bit ARM
