### ISSUE TITLE
Request to add Conv1d related operation

### ISSUE THREAD

**Issue by viggi1000** [pytorch/QNNPACK#48]
Hi, Kindly consider adding Conv1d, ConvTranspose1d and LSTM/RNN to the QNNPack library as it would greatly benefit development of mobile models which would work with time series sensor data for a variety of biomedical applications (ECG & wearables) and even benefit Human Activity Recognition using a phone's motion sensors. The reduced parameter needs of the aforementioned modules would be ideal in a mobile platform.

**Comment by hlu1** [comment]
You are welcome to contribute to QNNPACK.
