### ISSUE TITLE
What's the relationship between the ASM and C version micro kernel?

### ISSUE THREAD

**Issue by jackwish** [pytorch/QNNPACK#50]
Hi there,

I assume that C is for prototyping while ASM is the finally selected one. However, I found that the asm built from C looks to be unexpected when I am playing around.

Taking example https://github.com/pytorch/QNNPACK/blob/16fa9b2969f81fa49d1c47454b64a697e467b002/src/q8conv/8x8-neon.c#L74-L75 which generates asm sequence below (just an example, not the one peered the C code above) for Android ARM64 target.
```asm
dup v24.8h, v9.h[0]
ext v24.16b, v24.16b, v24.16b, #8
uxtl v24.8h, v24.8b
sub v27.8h, v24.8h, v29.8h
```

This is unexpected to me as the C code is using neon intrinsics. The generated asm instructions of C is about 1.5x of asm kernel. If this is expected, or I need to fix my build environment?

Thanks and Regards

**Comment by jackwish** [comment]
It seems that for https://github.com/pytorch/QNNPACK/blob/16fa9b2969f81fa49d1c47454b64a697e467b002/src/q8conv/8x8-neon.c#L77-L78, line 78 fails to generate asm like `smlal v8.4s, v27.4h, v0.h[0]`, but with
```asm
dup▸v24.8h, v13.h[0]
ext▸v24.16b, v24.16b, v24.16b, #8
smlal▸v19.4s, v28.4h, v24.4h
```
while L78 is correctly generated.

**Comment by jackwish** [comment]
close as i think the owner doesn't care :)

**Comment by Maratyszcza** [comment]
This is due to a recently fixed LLVM bug, see https://bugs.llvm.org/show_bug.cgi?id=40632

**Comment by Maratyszcza** [comment]
Also, see https://bugs.llvm.org/show_bug.cgi?id=40025 for another related bug

**Comment by jackwish** [comment]
Thank you @Maratyszcza That's really helpful :)

**Comment by jackwish** [comment]
Btw, I think https://github.com/pytorch/QNNPACK/blob/16fa9b2969f81fa49d1c47454b64a697e467b002/src/q8conv/8x8-aarch64-neon.S#L119-L200 obtains *one element* from `va{i}[0]`, though I fail to understand the usage from https://developer.arm.com/docs/100069/0606/a64-simd-vector-instructions/smlal-smlal2-vector which seems tell vector*vector only. (I am lake of ARM platform asm knowledge :( )
