### ISSUE TITLE
Typo in the announcement blog?

### ISSUE THREAD

**Issue by jackwish** [pytorch/QNNPACK#55]
Hi there,

I am wondering if the figure (as below) which describes matrix-matrix multiplication of the [announcement blog](https://code.fb.com/ml-applications/qnnpack/) has a typo?

![gemm](https://code.fb.com/wp-content/uploads/2018/10/QNNPACK1_final1.png)

In matrix B (`KxN`), the highlighted is the reduction dimension which should be **K** rather than **N**?

@hlu1

**Comment by Maratyszcza** [comment]
Good catch! The number of **columns** in B is **N**
