### ISSUE TITLE
How use the QNNPACK in PyTorch1.0 ?

### ISSUE THREAD

**Issue by Aspirinkb** [pytorch/QNNPACK#6]
QNNPACK is integrated in PyTorch 1.0, so how should one use it in PyTorch? Where can I find a tutorial?

**Comment by jspisak** [comment]
@Aspirinkb - we are still developing the API to expose this library through the PyTorch frontend. As we mention in the blog post, you can currently test through the Caffe2 interface and in the future through PyTorch. Sorry if the HN article title was misleading as it wasn't a core PyTorch lead that posted that.

**Comment by Aspirinkb** [comment]
Okay, I see. Thanks for your replay. I'm looking forward to seeing the QNNPACK in the PyTorch! It will be a great work.
