### ISSUE TITLE
Handler of variate in creating convolution23_nhwc_q8 function

### ISSUE THREAD

**Issue by JSnobody** [pytorch/QNNPACK#7]
I think it is necessary to add hander of output scale in qnnp_create_convolution2d_nhwc_q8, convolution.c.
Before the code, const float convolution_scale = input_scale * kernel_scale / output_scale;
we should judge of the value of output_scale and avoid ZERO.
Thanks.

**Comment by Maratyszcza** [comment]
Good point! Fixed in master revision.
