### ISSUE TITLE
How to use QNNPACK on iOS?

### ISSUE THREAD

**Issue by hcsearch** [pytorch/QNNPACK#9]
I compiled QNNPACK iOS library, now I want to run on iOS with the caffe2 model.but I don't know how to use it.do you have some sample on iOS or some  tutorial?

**Comment by Maratyszcza** [comment]
Here's a tutorial on mobile integration of Caffe2: https://caffe2.ai/docs/mobile-integration.html The tutorial is focused on Android, but Caffe2 is cross-platform, and the same code snippets should work on iOS as well.
